---
root: true
env:
  mocha: true
extends: standard
plugins:
  - mocha
  - chai-friendly
rules:
  "no-console": error
  "mocha/no-exclusive-tests": error
  "mocha/no-skipped-tests": error
  "mocha/no-identical-title": error
  "no-unused-expressions": off
  "chai-friendly/no-unused-expressions": error
