FORMAT: 1A
HOST: https://apiparticulier.sgmap.fr/

# API Particulier

Récupérez en ligne les informations de vos citoyens

# Group Impots

## Service de vérification de l'avis d'impôt sur le revenu [/api/impots/svair{?numeroFiscal}{?referenceAvis}]
Le service permet de vérifier l'authenticité du justificatif d'impôt sur le revenu ou de l'avis d'impôt sur le revenu présenté par un usager




### Affiche une déclaration [GET]
+ Parameters
    + numeroFiscal: `475757686` (number, required) - Numéro fiscal
    + referenceAvis: `768585` (number, required) - Référence d'avis

+ Request

    + Headers

            X-API-Key: correct-key
            Accept: application/json



+ Response 200 (application/json)


        {
          "declarant1": {
            "nom": "MARTIN",
            "nomNaissance": "MARTIN",
            "prenoms": "HENRI",
            "dateNaissance": "29/05/1984"
          },
          "declarant2": {
            "nom": "",
            "nomNaissance": "",
            "prenoms": "",
            "dateNaissance": ""
          },
          "foyerFiscal": {
            "annee": 2015,
            "adresse": "52 AVENUE DES CHAMPS ELYSEE 75009 PARIS"
          },
          "dateRecouvrement": "31/07/2015",
          "dateEtablissement": "08/07/2015",
          "nombreParts": 1,
          "situationFamille": "Célibataire",
          "nombrePersonnesCharge": 0,
          "revenuBrutGlobal": 17580,
          "revenuImposable": 17580,
          "impotRevenuNetAvantCorrections": 1665,
          "montantImpot": 1665,
          "revenuFiscalReference": 17580,
          "anneeImpots": "2015",
          "anneeRevenus": "2014"
        }


+ Request

    + Headers

            X-API-Key: correct-key
            Accept: application/xml



+ Response 200 (text/xml)


        <?xml version="1.0" encoding="UTF-8"?>
        <result>
        	<declarant1>
        		<nom>MARTIN</nom>
        		<nomNaissance>MARTIN</nomNaissance>
        		<prenoms>HENRI</prenoms>
        		<dateNaissance>29/05/1984</dateNaissance>
        	</declarant1>
        	<declarant2>
        		<nom></nom>
        		<nomNaissance></nomNaissance>
        		<prenoms></prenoms>
        		<dateNaissance></dateNaissance>
        	</declarant2>
          <foyerFiscal>
            <annee>2015</annee>
            <adresse>52 AVENUE DES CHAMPS ELYSEE 75009 PARIS</adresse>
          </foyerFiscal>
        	<dateRecouvrement>31/07/2015</dateRecouvrement>
        	<dateEtablissement>08/07/2015</dateEtablissement>
        	<nombreParts>1</nombreParts>
        	<situationFamille>Célibataire</situationFamille>
        	<nombrePersonnesCharge>0</nombrePersonnesCharge>
        	<revenuBrutGlobal>17580</revenuBrutGlobal>
        	<revenuImposable>17580</revenuImposable>
        	<impotRevenuNetAvantCorrections>1665</impotRevenuNetAvantCorrections>
        	<montantImpot>1665</montantImpot>
        	<revenuFiscalReference>17580</revenuFiscalReference>
        	<anneeImpots>2015</anneeImpots>
        	<anneeRevenus>2014</anneeRevenus>
        </result>

+ Request

    + Headers

            X-API-Key: badKey
            Accept: application/xml


+ Response 401 (text/xml)


        <?xml version="1.0" encoding="UTF-8"?>
        <error>
          <error>unauthorized</error>
          <reason>You are not authorized to use the api</reason>
        </error>

+ Request

    + Headers

            X-API-Key: badKey


+ Response 401 (application/json)


        {
          "error": "unauthorized",
          "reason": "You are not authorized to use the api"
        }


+ Request

    + Headers

            X-API-Key: correct-key



+ Response 404 (application/json)


        {
          "error": "not_found",
          "reason": "Les paramètres fournis sont incorrects ou ne correspondent pas à un avis"
        }


# Group Caf

## Attestation de la Caf [/api/caf/attestation{?codeOrganisme}{?numeroAllocataire}]

Permet de récupérer les attestations de CAF

+ Parameters
    + codeOrganisme: `toto` (string, required) - code la caisse de la caf
    + numeroAllocataire: `475757686` (string, required) - numéro de l'allocataire

### Affiche une déclaration [GET]

+ Request

    + Headers

            X-API-Key: <api-key>


+ Response 200 (application/pdf)


+ Request

    + Headers

            X-API-Key: badKey


+ Response 401 (application/json)


        {
          "error": "unauthorized",
          "reason": "You are not authorized to use the api"
        }
