swagger: '2.0'
info:
  title: API PARTICULIER
  description: |
    Bienvenue sur la documentation exécutable d'API Particulier

    #### Environnements

    Il existe plusieurs environnements:

    |             | Domain                       | Documentation                                     | API Key     | Stable |
    |-------------|------------------------------|---------------------------------------------------|-------------|--------|
    | Production  | particulier.api.gouv.fr      |[Lien](https://particulier.api.gouv.fr/docs/)      | Secret      | Oui    |
    | Test        | particulier-test.api.gouv.fr |[Lien](https://apiparticulier-test.sgmap.fr/docs/) | `test-token`| Oui    |
    | Dev         | particulier-dev.api.gouv.fr  |[Lien](https://apiparticulier-dev.sgmap.fr/docs/)  | Secret      | Non    |
    | Mocks       | particulier-mock.api.gouv.fr |[Lien](https://apiparticulier-mock.sgmap.fr/docs/) | ``          | Oui    |

    La documentation ci-dessous propose des données bidons pour faire des tests avec le token `test-token`.

    Pour la caf vous pouvez utiliser le numéro d'allocataire `0000354` et le département `99148`.
    Pour les impots vous pouvez utiliser le numéro fiscal `1562456789521` et la référence d'avis `1512456789521`.

    Essayez par vous-même !
  version: 1.0.0
basePath: /api
schemes:
  - https
produces:
  - application/json
  - application/xml
paths:
  /impots/svair:
    get:
      summary: Service de vérification de l'avis d'impôt sur le revenu
      description: |
        Le service permet de vérifier l'authenticité du justificatif d'impôt sur
        le revenu ou de l'avis d'impôt sur le revenu présenté par un usager
      parameters:
        - name: numeroFiscal
          in: query
          description: Numéro fiscal
          required: true
          type: number
          format: integer
        - name: referenceAvis
          in: query
          description: Référence d'avis
          required: true
          type: string
        - name: X-API-Key
          in: header
          description: Token d'identification de l'API
          required: true
          type: string
        - name: X-User
          in: header
          description: Utilisateur final de l'API
          required: false
          type: string
      tags:
        - Impots
      responses:
        '200':
          description: A declaration
          schema:
            $ref: '#/definitions/Declaration'
        '401':
          description: Le token ne vous permet pas d'accéder à l'API
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: 'Les paramètres fournis sont incorrects ou ne correspondent pas à un avis'
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /impots/adress:
    get:
      summary: Service pour récupérer l'adresse du foyer fiscal
      description: |
        permet de récupérer les possibles localisations du foyer fiscal
        enrichies grace à la BAN
      parameters:
        - name: numeroFiscal
          in: query
          description: Numéro fiscal
          required: true
          type: number
          format: integer
        - name: referenceAvis
          in: query
          description: Référence d'avis
          required: true
          type: string
        - name: X-API-Key
          in: header
          description: Token d'identification de l'API
          required: true
          type: string
        - name: X-User
          in: header
          description: Utilisateur final de l'API
          required: false
          type: string
      tags:
        - Impots
      responses:
        '200':
          description: A declaration
          schema:
            $ref: '#/definitions/SvairAdresses'
        '401':
          description: Le token ne vous permet pas d'accéder à l'API
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: 'Les paramètres fournis sont incorrects ou ne correspondent pas à un avis'
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'


  /caf/qf:
    get:
      summary: Quotient familial de la CAD
      description: |
        Le service permet de récupérer le quotient familial, sa date de calcul et les allocataires.
      parameters:
          - name: numeroAllocataire
            in: query
            description: Numéro d'allocataire
            required: true
            type: number
            format: integer
          - name: codePostal
            in: query
            description: Code postal
            required: true
            type: number
            format: integer
          - name: X-API-Key
            in: header
            description: Token d'identification de l'API
            required: true
            type: string
          - name: X-User
            in: header
            description: Utilisateur final de l'API
            required: false
            type: string
      tags:
        - CAF
      responses:
        '200':
          description: Le quotient familial
          schema:
            $ref: '#/definitions/QuotientFamilial'
        '401':
          description: Le token ne vous permet pas d'accéder à l'API
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: 'Les paramètres fournis sont incorrects ou ne correspondent pas à un allocataire CAF'
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /caf/adresse:
    get:
      summary: Adresse des allocataires de la caf
      description: |
        Le service permet de récupérer l'adresse, et les allocataires.
      parameters:
          - name: numeroAllocataire
            in: query
            description: Numéro d'allocataire
            required: true
            type: number
            format: integer
          - name: codePostal
            in: query
            description: Code postal
            required: true
            type: number
            format: integer
          - name: X-API-Key
            in: header
            description: Token d'identification de l'API
            required: true
            type: string
          - name: X-User
            in: header
            description: Utilisateur final de l'API
            required: false
            type: string
      tags:
        - CAF
      responses:
        '200':
          description: Le quotient familial
          schema:
            $ref: '#/definitions/CafAdresse'
        '401':
          description: Le token ne vous permet pas d'accéder à l'API
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: 'Les paramètres fournis sont incorrects ou ne correspondent pas à un allocataire CAF'
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /caf/famille:
    get:
      summary: Composition d'un foyer CAF
      description: |
        Le service permet de récupérer les parents et les enfants du foyer déclaré à la CAF.
        Il récupère leur nom et prénom, leur date de naissance et leur sexe.
      parameters:
          - name: numeroAllocataire
            in: query
            description: Numéro d'allocataire
            required: true
            type: number
            format: integer
          - name: codePostal
            in: query
            description: Code Postal
            required: true
            type: number
            format: integer
          - name: X-API-Key
            in: header
            description: Token d'identification de l'API
            required: true
            type: string
          - name: X-User
            in: header
            description: Utilisateur final de l'API
            required: false
            type: string
      tags:
        - CAF
      responses:
        '200':
          description: Le quotient familial
          schema:
            $ref: '#/definitions/Famille'
        '401':
          description: Le token ne vous permet pas d'accéder à l'API
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: 'Les paramètres fournis sont incorrects ou ne correspondent pas à un allocataire CAF'
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /ping:
    get:
      summary: Service pour connaitre si l'application fonctionne correctement
      tags:
        - System
      responses:
        '200':
          description: Un
          schema:
            type: string
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'


definitions:
  Declaration:
    type: object
    properties:
      declarant1:
        $ref: '#/definitions/Declarant'
      foyerFiscal:
        $ref: '#/definitions/FoyerFiscal'
      declarant2:
        $ref: '#/definitions/Declarant'
      dateRecouvrement:
        type: string
        description: 'Date de recouvrement; format: JJ/MM/AAA'
      dateEtablissement:
        type: string
        description: 'Date de recouvrement; format: JJ/MM/AAA'
      nombreParts:
        type: integer
        description: 'Nombre de parts'
      situationFamille:
        type: string
        description: Situation familiale (marié, célibataire...)
      nombrePersonnesCharge:
        type: integer
        description: 'Nombre de personne à charge '
      revenuBrutGlobal:
        type: integer
        description: 'Revenu brut global'
      revenuImposable:
        type: integer
        description: 'Revenu imposable'
      impotRevenuNetAvantCorrections:
        type: integer
        description: 'Revenu net avant correction'
      montantImpot:
        type: integer
        description: 'Montant des impots'
      revenuFiscalReference:
        type: integer
        description: 'Revenu fiscal de référence'
      anneeImpots:
        type: integer
        description: 'Année format: AAAA'
      anneeRevenus:
        type: integer
        description: 'Année format: AAAA'

  SvairAdresses:
    type: object
    properties:
      declarant1:
        $ref: '#/definitions/Declarant'
      foyerFiscal:
        $ref: '#/definitions/FoyerFiscal'
      declarant2:
        $ref: '#/definitions/Declarant'
      adresses:
        type: array
        items:
          $ref: '#/definitions/Address'
  Address:
    type: object
    properties:
      adresse:
        type: object
        properties:
          name:
            type: string
          city:
            type: string
          housenumber:
            type: string
          label:
            type: string
          context:
            type: string
          citycode:
            type: string
          type:
            type: string
          score:
            type: number
            format: double
          postcode:
            type: string
      geometry:
        type: object
        properties:
          type:
            type: string
          coordinates:
            type: array
            items:
              type: number
              format: double

  Declarant:
    type: object
    properties:
      nom:
        type: string
        description: nom du déclarant
      nomNaissance:
        type: string
        description: nom de naissance du déclarant
      prenoms:
        type: string
        description: prenoms du déclarant
      dateNaissance:
        type: string
        description: dateNaissance du déclarant

  FoyerFiscal:
    type: object
    properties:
      annee:
        type: integer
        description: année
      adresse:
        type: string
        description: adresse fiscale de l'année passée


  QuotientFamilial:
    type: object
    properties:
      quotientFamilial:
        type: integer
        description: Quotient familial
      allocataires:
        type: array
        description: Noms et prénoms des personnes allocataire de la CAF
        items:
          type: string
      annee:
        type: integer
        description: Année du quotient familial
      mois:
        type: integer
        description: Mois du quotient familial

  CafAdresse:
    type: object
    description: L'adresse de la Caf
    properties:
      adresse:
        $ref: '#/definitions/PosteAdresse'
      allocataires:
        type: array
        description: Noms et prénoms des personnes allocataire de la CAF
        items:
          type: string
      annee:
        type: integer
        description: Année du quotient familial
      mois:
        type: integer
        description: Mois du quotient familial

  PosteAdresse:
    type: object
    description: Adresse au format de la poste
    properties:
      identite:
        type: string
        description: '<b>Identité du destinataire : </b>Civilité, titre ou qualité + nom et prénom'
      complementIdentite:
        type: string
        description: "<b>Complément d'information du destinataire ou point de remise : </b>Numéro d'appartement, Escalier"
      complementIdentiteGeo:
        type: string
        description: "<b>Complément d'information du point géographique : </b>Entrée, tour, immeuble, bâtiment, Résidence"
      numeroRue:
        type: string
        description: '<b>Numéro et libellé de la voie</b>'
      lieuDit:
        type: string
        description: '<b>Lieu-dit ou service particulier de distribution :</b> poste restante, boîte postale'
      codePostalVille:
        type: string
        description: '<b>Code postale et localité de destination</b>'
      pays:
        type: string
        description: '<b>Pays</b>'
  Person:
    type: object
    description: Personne référencée à la CAF
    properties:
      nomPrenon:
        type: array
        description: Noms et prénoms des personnes allocataires de la CAF
        items:
          type: string
      dateDeNaissance:
        type: string
        description: "Date de naissance au format: JJMMAAAA"
      sexe:
        type: string
        description: "'M' : masculin ou 'F' : féminin"

  Famille:
    description: Foyer tel qu'il est déclaré à la CAF
    type: object
    properties:
      allocataires:
        type: array
        items:
          $ref: '#/definitions/Person'
      enfants:
        type: array
        items:
          $ref: '#/definitions/Person'

  Error:
    type: object
    properties:
      message:
        type: string
      error:
        type: string
